//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerProxyService.Ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoggerEfContext : DbContext
    {
        public LoggerEfContext()
            : base("name=LoggerEfContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Device> Devices { get; set; }
        public DbSet<Platform> Platforms { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Registration> Registrations { get; set; }
    }
}
