//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerProxyService.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        public Platform()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public string PlatformName { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
    }
}
