//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerProxyService.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<System.DateTime> RegistrationTime { get; set; }
        public string AssemblyVersion { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Project Project { get; set; }
    }
}
